```{r, include=FALSE,echo=FALSE}


PAQUETES <- c("dplyr","tidyverse","ggplot2","ggalluvial","viridis","ggridges","fmsb","maps","treemap","forcats")

for (el in PAQUETES){
  if (!require(el, character.only = TRUE)) {
    install.packages(el)
    require(el, character.only = TRUE)
  }
}


rm(PAQUETES, el)
```

```{r}
data<-read_tsv("./data/datos_2019/EILU_GRADUADOS/CSV/EILU_GRAD_2019.csv")
```
recode data
```{r}
data %>% 
    mutate(RAMA = recode(RAMA,
                       `1` = "Arts and Humanities",
                       `2` = "Sciences",
                       `3` = "Social Sciences and Law",
                       `4` = "Engineering and Architecture",
                       `5` = "Health Sciences")) %>% 
    mutate(AMBITO = recode(AMBITO,
                         `0112` = "Education",
                         `0113` = "Education",
                         `011` = "Education",
                         `0211` = "Arts and Communication",
                         `021` = "Arts and Communication",
                         `022` = "Humanities",
                         `023` = "Languages",
                         `0311` = "Economics",
                         `0313` = "Psychology",
                         `031` = "Social Sciences",
                         `032` = "Journalism",
                         `0413` = "Business",
                         `041` = "Business",
                         `042` = "Law",
                         `051` = "Life Sciences",
                         `052` = "Environmental Science and Forestry",
                         `053` = "Physical Sciences",
                         `054` = "Mathematics and Statistics",
                         `061` = "Computer Science",
                         `071` = "Engineering",
                         `072` = "Manufacturing",
                         `073` = "Architecture",
                         `081` = "Agriculture",
                         `082` = "Environmental Science and Forestry",
                         `084` = "Veterinary",
                         `0912` = "Medicine",
                         `0913` = "Nursing",
                         `091` = "Health Sciences",
                         `092` = "Social Services",
                         `1014` = "Sports Education",
                         `1015` = "Tourism and Leisure",
                         `109` = "Other",
                         `9999` = "Not Specified")) %>% 
    mutate(TR_CNAE = recode(TR_CNAE,
                         `AA` = "Primary Sector",
                         `BB` = "Primary Sector",
                         `CC` = "Manufacturing",
                         `DD` = "Transport and Utilities",
                         `EE` = "Transport and Utilities",
                         `FF` = "Construction",
                         `GG` = "Trade and Repairs",
                         `HH` = "Transport and Utilities",
                         `II` = "Hospitality",
                         `JJ` = "Information and Comunication",
                         `KK` = "Finance and Real Estate",
                         `LL` = "Finance and Real Estate",
                         `M1` = "Professional Services",
                         `M2` = "Professional Services",
                         `M3` = "Professional Services",
                         `N1` = "Professional Services",
                         `N2` = "Professional Services",
                         `N3` = "Professional Services",
                         `N4` = "Professional Services",
                         `N5` = "Professional Services",
                         `N6` = "Professional Services",
                         `OO` = "Public Administration",
                         `PP` = "Education",
                         `QQ` = "Healthcare and Social Services",
                         `RR` = "Art and Entertainment",
                         `S1` = "Other Services",
                         `S2` = "Other Services",
                         `S3` = "Other Services",
                         `S4` = "Other Services",
                         `TT` = "Other Services",
                         `UU` = "Other Services",
                         `99` = "Not Available",
                         .default = NA_character_)) %>% 
    mutate(TRBPRN1 = recode(TRBPRN1,
                          `1` = "Working",
                          `2` = "Unemployed",
                          `3` = "Inactive")) %>% 
    mutate(LUG_TRAB_PAIS = factor(recode(LUG_TRAB_PAIS,
                         `01` = "Spain",
                         `02` = "United Kingdom",
                         `03` = "Germany",
                         `04` = "France",
                         `05` = "Other EU",
                         `06` = "Rest of Europe",
                         `07` = "North America",
                         `08` = "Central and South America",
                         `09` = "Asia and Oceania",
                         `10` = "Africa",
                         `11` = "Asia and Oceania",
                         `99` = "NS/NC", # Not Specified / Not Categorized
                         .default = "Not applicable"))) %>% 
  mutate(TR_SUELDO_string=recode(TR_SUELDO,
                           `1` = "<700",
                               `2` = "700-999",
                               `3` = "1,000-1,499",
                               `4` = "1,500-1,999",
                               `5` = "2,000-2,499",
                               `6` = "2,500-2,999",
                               `7` = ">3,000",
                               `9` = "NA")) %>% 
  mutate(TR_CNAE = case_when(
    TRBPRN1 == 'Inactive' ~ 'Inactive',
    TRBPRN1 == 'Unemployed' ~ 'Unemployed',
    TRUE ~ TR_CNAE
  )) -> data_recoded
```


Alluvial plot from field of studies to sector
```{r}
data_recoded %>% select(RAMA,AMBITO,TRBPRN1, TR_CNAE,FACTOR) %>% 
  group_by(AMBITO,TR_CNAE) %>% 
  summarise(FACTOR=sum(FACTOR)) %>% 
  mutate(AMBITO=factor(AMBITO))-> educ_activity

# Manually reorder FACTOR levels
#TODO: Do this for AMBITO
educ_activity$RAMA <- fct_relevel(educ_activity$RAMA,
                                   "Arts and Humanities",
                                   "Sciences",
                                   "Social Sciences and Law",
                                   "Engineering and Architecture",
                                   "Health Sciences"
                                   )

educ_activity %>%
  ggplot(aes(axis1 = AMBITO, axis2 = TR_CNAE, y = FACTOR)) +
  geom_alluvium(aes(fill = AMBITO)) +
  geom_stratum(color="grey30") +
  geom_text(stat = "stratum", aes(label = after_stat(stratum)), size = 3.5) + 
  labs(
    title = "Educational Background and Sector of Employment",
    x = "",
    y = "",
    caption = "Source: INE, Survey on the labour market insertion of university graduates"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    plot.title = element_text(size=20, face="bold"),
    axis.text.x = element_blank(),
    axis.text.y = element_text(size=14),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.position = "none",
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    # panel.background = element_rect(fill="white", colour="black"),
    # plot.background = element_rect(fill="white", colour="black"),
    plot.margin = margin(20, 20, 20, 20)
  ) -> alluvial

ggsave("./plots/alluvial.pdf",alluvial,width=8,height=15,units="in")
```

expats by education and country
```{r}
data_recoded %>%
  group_by(AMBITO, LUG_TRAB_PAIS) %>%
  # Calculate the sum of FACTOR for each group
  summarize(total_factor = sum(FACTOR, na.rm = TRUE),
            RAMA=names(which.max(table(RAMA)))) %>%
  ungroup() %>%
  # Calculate the sum of FACTOR for each AMBITO across all LUG_TRAB_PAIS
  group_by(AMBITO) %>%
  mutate(total_ambito = sum(total_factor, na.rm = TRUE),
         RAMA=names(which.max(table(RAMA)))) %>%
  # Calculate the percentage of each row's factor over its AMBITO's total
  mutate(percentage = (total_factor / total_ambito) * 100) %>%
  ungroup() %>% 
  mutate(EXPAT=case_when(
  LUG_TRAB_PAIS %in% c("Spain",NA) ~ "Spain",
  TRUE ~"Expat"
  )) %>% 
  filter(EXPAT=="Expat") %>%
  select(RAMA,AMBITO,LUG_TRAB_PAIS,percentage)-> expat

unique_ambito <- expat %>% distinct(AMBITO) %>% pull(AMBITO)
unique_pais <- expat %>% distinct(LUG_TRAB_PAIS) %>% pull(LUG_TRAB_PAIS)

# Create a data frame of all possible combinations
all_combinations <- expand.grid(AMBITO = unique_ambito, LUG_TRAB_PAIS = unique_pais)

# Left join with your expat data to include all combinations
# Rows in all_combinations that don't match will have NA for 'percentage'
# which we then replace with 0
expat <- all_combinations %>%
  left_join(expat, by = c("AMBITO", "LUG_TRAB_PAIS")) %>%
  mutate(percentage = if_else(is.na(percentage), 0, percentage))


# Set a number of 'empty bar' to add at the end of each group
empty_bar <- 2
nObsType <- nlevels(as.factor(expat$LUG_TRAB_PAIS))
to_add <- data.frame( matrix(NA, empty_bar*nlevels(expat$RAMA)*nObsType, ncol(expat)) )
colnames(to_add) <- colnames(expat)
to_add$RAMA <- rep(levels(expat$RAMA), each=empty_bar*nObsType )
expat <- rbind(expat, to_add)
expat <- expat %>% arrange(RAMA, AMBITO)
expat$id <- rep( seq(1, nrow(expat)/nObsType) , each=nObsType)

# Get the name and the y position of each label
label_data <- expat %>% group_by(id,AMBITO) %>% summarize(tot=sum(percentage))
number_of_bar <- nrow(label_data)
angle <- 90 - 360 * (label_data$id-0.5) /number_of_bar     # I substract 0.5 because the letter must have the angle of the center of the bars. Not extreme right(1) or extreme left (0)
label_data$hjust <- ifelse( angle < -90, 1, 0)
label_data$angle <- ifelse(angle < -90, angle+180, angle)

# prepare a data frame for base lines
base_data <- expat %>% 
  group_by(LUG_TRAB_PAIS) %>% 
  summarize(start=min(id), end=max(id) - empty_bar) %>% 
  rowwise() %>% 
  mutate(title=mean(c(start, end)))

# prepare a data frame for grid (scales)
grid_data <- base_data
grid_data$end <- grid_data$end[ c( nrow(grid_data), 1:nrow(grid_data)-1)] + 1
grid_data$start <- grid_data$start - 1
grid_data <- grid_data[-1,]

ggplot(expat) +      
  # Add the stacked bar
  geom_bar(aes(x=as.factor(id), y=percentage, fill=LUG_TRAB_PAIS), stat="identity", alpha=0.5) +
  scale_fill_viridis(discrete=TRUE) +
    # Add a val=100/75/50/25 lines. I do it at the beginning to make sur barplots are OVER it.
  geom_segment(data=grid_data, aes(x = end, y = 0, xend = start, yend = 0), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data, aes(x = end, y = 5, xend = start, yend = 5), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data, aes(x = end, y = 10, xend = start, yend = 10), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
    geom_segment(data=grid_data, aes(x = end, y = 15, xend = start, yend = 15), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
  geom_segment(data=grid_data, aes(x = end, y = 20, xend = start, yend = 20), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
    # Add text showing the value of each  lines
  ggplot2::annotate("text", x = rep(max(data$id),5), y = c(0, 5, 10,15, 20), label = c("0", "5", "10", "15", "20") , color="grey", size=6 , angle=0, fontface="bold", hjust=1) +
    ylim(-20,20) +
    theme_minimal() +
  theme(
    legend.position = "none",
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = unit(rep(-1,4), "cm") 
  ) +
   coord_polar()



```








try normal barplot for expats
```{r}
data_recoded %>%
  group_by(AMBITO, LUG_TRAB_PAIS) %>%
  # Calculate the sum of FACTOR for each group
  summarize(total_factor = sum(FACTOR, na.rm = TRUE),
            RAMA=names(which.max(table(RAMA)))) %>%
  ungroup() %>%
  # Calculate the sum of FACTOR for each AMBITO across all LUG_TRAB_PAIS
  group_by(AMBITO) %>%
  mutate(total_ambito = sum(total_factor, na.rm = TRUE),
         RAMA=names(which.max(table(RAMA)))) %>%
  # Calculate the percentage of each row's factor over its AMBITO's total
  mutate(percentage = (total_factor / total_ambito) * 100) %>%
  ungroup() %>% 
  mutate(EXPAT=case_when(
  LUG_TRAB_PAIS %in% c("Spain",NA) ~ "Spain",
  TRUE ~"Expat"
  )) %>% 
  filter(EXPAT=="Expat") %>%
  select(RAMA,AMBITO,LUG_TRAB_PAIS,percentage,total_factor) %>% 
  group_by(AMBITO) %>% 
  mutate(total_expats=sum(percentage)) %>% 
  ungroup() %>% 
  mutate(LUG_TRAB_PAIS=fct_recode(LUG_TRAB_PAIS,
                                     "Not Available" = "NS/NC"))%>% 
  mutate(LUG_TRAB_PAIS = factor(LUG_TRAB_PAIS, levels = rev(c("United Kingdom", 
                                                          "Germany", 
                                                          "France",
                                                          "Other EU",
                                                          "Rest of Europe",
                                                          "North America",
                                                          "Central and South America",
                                                          "Asia and Oceania",
                                                          "Africa",
                                                          "Not Available"
                                                          ))))-> expat



expat %>% 
  ggplot(aes(x=reorder(AMBITO,-total_expats), y=percentage, fill=LUG_TRAB_PAIS)) +
  geom_col() +
  scale_fill_brewer(palette="Set3") +  # You might want to choose a palette that matches your previous plot's style
  labs(
    title = "Expat Distribution by Field of Study and Country",
    x = "Percentage of Recent Graduates Employed",
    y = "",
    caption = "Source: INE, Survey on the labour market insertion of university graduates"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    plot.title = element_text(size=20, face="bold"),  
    axis.title.x = element_text(size=16, face="bold", color="grey30"),
    axis.text.x = element_text(size=14, hjust = 1),  # Adjust text angle and justification as needed
    axis.text.y = element_text(size=14),
    legend.position="bottom",
    legend.title = element_blank(),
    legend.text = element_text(size=14, color="grey30"), 
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill="white", colour="black"),
    plot.background = element_rect(fill="white", colour="black"),
    plot.margin = margin(20, 20, 20, 20)
  )
```
expat map
```{r}
data_recoded %>% 
  select(RAMA,LUG_TRAB_PAIS,FACTOR) %>% 
  filter(LUG_TRAB_PAIS!="Spain") %>% 
  group_by(RAMA,LUG_TRAB_PAIS) %>% 
  summarise(factor=sum(FACTOR)) %>% 
  mutate(
    lat = case_when(
      LUG_TRAB_PAIS == 'Central and South America' ~ -12.0,
      LUG_TRAB_PAIS == 'France' ~ 46.0,
      LUG_TRAB_PAIS == 'Germany' ~ 51.0,
      LUG_TRAB_PAIS == 'North America' ~ 37.0,
      LUG_TRAB_PAIS == 'Other EU' ~ 50.0,
      LUG_TRAB_PAIS == 'Rest of Europe' ~ 54.0,
      LUG_TRAB_PAIS == 'United Kingdom' ~ 55.4,
      LUG_TRAB_PAIS == 'Africa' ~ -8.0,
      LUG_TRAB_PAIS == 'Asia and Oceania' ~ -8.0,
      LUG_TRAB_PAIS == 'Central and South America' ~ -12.0,
      TRUE ~ NA_real_ # default case
    ),
    lon = case_when(
      LUG_TRAB_PAIS == 'Central and South America' ~ -77.0,
      LUG_TRAB_PAIS == 'France' ~ 2.0,
      LUG_TRAB_PAIS == 'Germany' ~ 10.0,
      LUG_TRAB_PAIS == 'North America' ~ -95.0,
      LUG_TRAB_PAIS == 'Other EU' ~ 10.0,
      LUG_TRAB_PAIS == 'Rest of Europe' ~ 25.0,
      LUG_TRAB_PAIS == 'United Kingdom' ~ -3.4,
      LUG_TRAB_PAIS == 'Africa' ~ 34.0,
      LUG_TRAB_PAIS == 'Asia and Oceania' ~ 120.0,
      LUG_TRAB_PAIS == 'Central and South America' ~ -77.0,
      TRUE ~ NA_real_ # default case
    )
  ) -> map
  
map %>% 
ggplot(aes(x = lon, y = lat, size = factor, color = RAMA)) +
  borders("world", colour = "gray85", fill = "gray80") + 
  geom_point(alpha = 0.5) + 
  scale_size(range = c(3, 20)) +
  theme_minimal() +
  labs(title = "Bubble Map by RAMA", x = "Longitude", y = "Latitude", size = "Factor") +
  theme(legend.position = "right") +
  coord_fixed(1.3) +
  xlim(-10, 40) + ylim(35, 70)


##MUY FEO; igual otra opcion es hacer bubbles o donuts y colocarlos manualmente
```



treemap expats
```{r}
map %>% 
treemap(index=c("LUG_TRAB_PAIS", "RAMA"), # Nesting first by country, then by RAMA
        vSize="factor", # Size of the rectangles based on the 'factor' column
        vColor="factor", # Coloring based on the 'factor' column, can adjust as needed
        title="Treemap by Country and RAMA",
        fontsize.title=20,
        palette="Spectral", # Color palette, can adjust as needed
        border.col="white", # Color of the borders between rectangles
        fontcolor.labels=c("black"), # Color of the labels
        fontface.labels=1, # Font face of the labels
        fontsize.labels=c(12,10), # Size of the labels, adjust as needed
        as.table=TRUE) # Arrange the treemap as a table
```



bubbles expat
```{r}
map %>% 
  group_by(LUG_TRAB_PAIS) %>% 
  summarise(factor=sum(factor)) %>% 
  filter(LUG_TRAB_PAIS!="NS/NC") %>% 
  mutate(total_expats=sum(factor)) %>% 
  mutate(perc_expats=factor/total_expats*100) %>% 
    mutate(
    X = case_when(
      LUG_TRAB_PAIS == "Africa" ~ 4,
      LUG_TRAB_PAIS == "Asia and Oceania" ~ 6,
      LUG_TRAB_PAIS == "Central and South America" ~ 2,
      LUG_TRAB_PAIS == "France" ~ 4,
      LUG_TRAB_PAIS == "Germany" ~ 5,
      LUG_TRAB_PAIS == "North America" ~ 2,
      LUG_TRAB_PAIS == "NS/NC" ~ 0,
      LUG_TRAB_PAIS == "Other EU" ~ 4.5,
      LUG_TRAB_PAIS == "Rest of Europe" ~ 4.5,
      LUG_TRAB_PAIS == "United Kingdom" ~ 3.5
    ),
    Y = case_when(
      LUG_TRAB_PAIS == "Africa" ~ 0.5,
      LUG_TRAB_PAIS == "Asia and Oceania" ~ 1,
      LUG_TRAB_PAIS == "Central and South America" ~ 0.5,
      LUG_TRAB_PAIS == "France" ~ 1,
      LUG_TRAB_PAIS == "Germany" ~ 1.2,
      LUG_TRAB_PAIS == "North America" ~ 2.5,
      LUG_TRAB_PAIS == "NS/NC" ~ 0,
      LUG_TRAB_PAIS == "Other EU" ~ 1.7,
      LUG_TRAB_PAIS == "Rest of Europe" ~ 1,
      LUG_TRAB_PAIS == "United Kingdom" ~ 1.8
    )
  ) -> bubbles


bubbles %>%
  ggplot(aes(x = X, y = Y, size = perc_expats)) +
  geom_point(alpha = 0.6,color = c("#1b9e77")) +  # Transparency for the bubbles
  geom_text(aes(label = LUG_TRAB_PAIS), vjust = -1.5, hjust = 0.5, color="grey30", size = 4.5) +  # Text labels
  scale_size_continuous(range = c(15, 32)) +  # Adjust bubble size
  theme_minimal(base_size = 14) +  # Base theme for minimal style
  labs(
    title = "Bubble Chart of Work Locations by Region",
    x = "",
    y = "",
    size = "Percentage of total expats",
    caption = "Source: INE, Survey on the labour market insertion of university graduates"

  ) +
  theme(
    plot.title = element_text(size=20, face="bold"),
    axis.text.x = element_blank(),  # Remove axis text
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),  # Remove axis ticks
    axis.title.x = element_blank(),  # Remove axis titles
    axis.title.y = element_blank(),
    legend.position = "right",
    legend.title = element_text(size=14, color="grey30"),
    legend.text = element_text(size=14, color="grey30"),
    panel.grid.major = element_blank(),  # Remove gridlines
    panel.grid.minor = element_blank(),
    panel.background = element_rect(colour="black"),

    panel.border = element_blank(),  # Remove panel border
    plot.background = element_rect(fill="white", colour="black"),  # White plot background with black border
    plot.margin = margin(20, 20, 20, 20)  # Adjust plot margins
  ) +
  ylim(c(0, 4)) + 
  xlim(c(0, 8))    ->bubbles_plot

ggsave("./plots/bubbles.pdf",bubbles_plot,width=8,height=5,units="in")

```





reasons to expat
```{r}
data_recoded %>%
  filter(LUG_TRAB_PAIS!="Spain") %>% 
  select(IDENT,AMBITO,FACTOR,LUG_TRAB_PAIS,MOVRA21,
                              MOVRA22,
                              MOVRA23,
                              MOVRA24,
                              MOVRA25,
                              MOVRA26,
  ) %>% pivot_longer(cols=c("MOVRA21",
                              "MOVRA22",
                              "MOVRA23",
                              "MOVRA24",
                              "MOVRA25",
                              "MOVRA26"),names_to = "motive",values_to = "value") %>% 
  mutate(motive=recode(motive,
                       "MOVRA21"="Found a job",
                       "MOVRA22"="Job searching or other economic reason",
                       "MOVRA23"="Academic reasons",
                       "MOVRA24"="Personal reasons",
                       "MOVRA25"="Administrative reasons",
                       "MOVRA26"="Other reasons",
                       )) %>% 
  mutate(value=case_when(
    value==1 ~ FACTOR,
    TRUE ~0
  )) %>% 
  group_by(AMBITO,motive) %>% 
  summarise(value=sum(value),FACTOR=sum(FACTOR)) %>% 
  ungroup() %>% 
  mutate(percentage=value/FACTOR*100) %>% 
  filter(motive!="Administrative reasons") %>% 
  group_by(AMBITO) %>% 
  mutate(max_reason=max(percentage),
         min_reason=min(percentage)
         ) %>% 
  ungroup() %>% 
  left_join(
    expat %>% 
      select(AMBITO,total_expats) %>% 
      group_by(AMBITO) %>% 
      summarise(total_expats=first(total_expats)),
    by="AMBITO"
  )  -> reasons_expat
  
scale_factor=max(reasons_expat$percentage)/max(reasons_expat$total_expats)
  
reasons_expat %>%
  ggplot(aes(y=reorder(AMBITO, total_expats))) +
  geom_bar(aes(x=total_expats), stat="identity", fill="grey80") +  
  geom_point(aes(x=percentage, color=motive,shape=motive), size=3) +  
  geom_segment( aes(x=min_reason, xend=max_reason),color = "gray50", size = .1) +
  scale_color_manual(values=c("Academic reasons"="#1b9e77",
                              "Found a job"="#d95f02", 
                              "Job searching or other economic reason"="#7570b3",
                              "Other reasons"="#e7298a",
                              "Personal reasons"="#66a61e")) +  # Set your color values
  scale_x_continuous("Reason for Expatriation (shapes)", 
                     sec.axis = sec_axis(~ . / scale_factor, 
                                         name = "Expat Rate (bars)",
                                         labels = function(x) paste0(x, "%")
                                        ),
                     labels = function(x) paste0(x, "%")
                     ) +
    scale_shape_manual(values=c(15, 16, 17, 18, 19)) + 
  labs(
    title = "Expat Distribution by Field of Study and Reason",
    x = "Percentage of Recent Graduates Employed",
    y = "",
    caption = "Source: INE, Survey on the labour market insertion of university graduates"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    plot.title = element_text(size=20, ),  
    axis.title.x = element_text(size=14, color="grey30"),
    axis.text.x = element_text(size=14),  # Use a smaller size for axis text for better readability
    axis.text.y = element_text(size=14),
    legend.position="right",
    legend.title = element_blank(),
    legend.text = element_text(size=14, color="grey30"), 
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill="white", colour="black"),
    plot.background = element_rect(fill="white", colour="black"),
    plot.margin = margin(20, 20, 20, 20)
  )
  

```




ridgeline wages
```{r}
data_recoded %>% 
  filter(TRBPRN1=="Working",
         TR_SUELDO!="9") %>% 
  select(AMBITO,TR_SUELDO,TR_SUELDO_string,FACTOR) %>% 
  group_by(AMBITO,TR_SUELDO,TR_SUELDO_string) %>% 
  summarise(factor=sum(FACTOR)) %>% 
  ungroup() %>% 
  mutate(order=as.numeric(TR_SUELDO)) %>% 
  group_by(AMBITO) %>% 
  mutate(percentage=factor/sum(factor)*100,
         order_category=(order%*%percentage)) %>% 
  ungroup()->wages

wages %>%
  ggplot(aes(y = reorder(AMBITO, order_category), x = reorder(TR_SUELDO_string, order), height = percentage, group = AMBITO)) +
  geom_density_ridges(stat = "identity",
                               scale = 2, 
                               fill="#1b9e77", #TODO: alternate colors in ilustrator
                              alpha=0.2) + 
  scale_x_discrete(name = "") +
  scale_y_discrete(name = "") +
  labs(
    title = "Distribution of Wages by Field of Study",
    subtitle = "Percentage within each wage bracket",
    caption = "Source: INE, Survey on the labour market insertion of university graduates"
  ) +
 theme(
    plot.title = element_text(size=20, face="bold"),
    plot.subtitle = element_text(size=16, color="grey30"),
    axis.text.x = element_text(size=14, hjust = 1, color="grey30"),
    axis.text.y = element_text(size=14, color="grey30"),
    legend.position = "none",
    panel.grid.major = element_line(size = 0.2, linetype = 'dotted', color = "grey80"),  # Adjust major gridlines
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_line(color = "grey80", size = 0.2),  # Enable vertical major gridlines
    panel.grid.major.y = element_blank(),  # Disable horizontal major gridlines if you want
    panel.background = element_blank(),
    plot.background = element_blank(),
    plot.margin = margin(20, 20, 20, 20)
  ) 

```






Use of knowledge in current job and overqualification
```{r}
data_recoded %>% 
  filter(TRBPRN1=="Working") %>% 
  select(AMBITO,TR_D21,FACTOR) %>% 
  mutate(factor_binary = ifelse(TR_D21==1,FACTOR,0)) %>% 
  group_by(AMBITO) %>% 
  summarise(
    total=sum(FACTOR),
    used_education=sum(factor_binary,na.rm=T)
  ) %>% 
  mutate(percentage_knowledge=used_education/total*100) %>% 
  mutate(AMBITO=factor(AMBITO,levels=AMBITO)) %>% 
  arrange(desc(percentage_knowledge)) ->used_knowledge

data_recoded %>% 
  filter(TRBPRN1=="Working") %>% #working
  select(AMBITO,TR_D19,FACTOR) %>% 
  mutate(factor_binary=case_when(
    TR_D19 %in% c(1,2,3) ~ 0,
    TRUE ~ FACTOR
  ))  %>% 
  group_by(AMBITO) %>% 
  summarise(
    total=sum(FACTOR),
    overqualified=sum(factor_binary,na.rm=T)
  ) %>% 
  mutate(overqual_perc=overqualified/total*100) ->overqualification

used_knowledge %>% 
  select(AMBITO,percentage_knowledge) %>% 
  left_join(overqualification,by="AMBITO") %>% 
  select(AMBITO,percentage_knowledge,overqual_perc) %>% 
  rename("Current work utilizes the knowledge and skills acquired in these studies"=percentage_knowledge,
         "Current work requires an education level lower than a university degree"=overqual_perc) %>% 
  pivot_longer(col=-AMBITO,names_to="names",values_to = "values") %>% 
  group_by(AMBITO) %>% 
  mutate(order=max(values)) %>% 
  ungroup() ->work_relevance

work_relevance %>% 
ggplot(aes(y=reorder(AMBITO, order), x=values)) +
  geom_line(color="gray80", size=1) + 
  geom_point(aes(color=names,shape=names), size=4) +  
  geom_text(aes(label=sprintf("%.1f%%", values),
                hjust=ifelse(names == "Current work utilizes the knowledge and skills acquired in these studies", -0.2, 1.2)), 
             vjust=0.3, size=5, color="grey30") +  
  scale_color_manual(values=c("Current work utilizes the knowledge and skills acquired in these studies"="#1b9e77",
                              "Current work requires an education level lower than a university degree"="#d95f02")) +
  scale_x_continuous(limits = c(-2,102),
                       breaks = c(0, 20, 40, 60, 80, 100),
                       labels = function(x) paste0(x, "%")) +  
  scale_shape_manual(values=c(17, 18)) +
  labs(
    title = "Relationship between Field of Study and Work Relevance",
    y = "",
    x = "Percentage of Recent Graduates Employed",
    caption = "Source: INE, Survey on the labour market insertion of university graduates"
  ) +
  theme_minimal(base_size = 14) +  
  theme(
    legend.position="bottom",
    legend.title = element_blank(),
    plot.title = element_text(size=20, face="bold"),  
    axis.title.x = element_text(size=14,color="grey30"),
    axis.text.x = element_text(size=14), 
    axis.text.y = element_text(size=14),
    legend.text = element_text(size=14,color="grey30"), 
    legend.box = "vertical",
    legend.direction = "vertical",
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill="white", colour="black"),
    plot.background = element_rect(fill="white", colour="black"),
    plot.margin = margin(20, 20, 20, 20)  
  ) +
  guides(color=guide_legend(title.position = "top", label.position = "right", ncol = 1))


```


factors to find job
```{r}
data_recoded %>%
  select(IDENT,AMBITO,FACTOR,TR_D22_1,
                                            TR_D22_2,
                                            TR_D22_3,
                                            TR_D22_4,
                                            TR_D22_5,
                                            TR_D22_6,
  ) %>% pivot_longer(cols=c("TR_D22_1",
                            "TR_D22_2",
                            "TR_D22_3",
                            "TR_D22_4",
                            "TR_D22_5",
                            "TR_D22_6",
                            ),names_to = "reason",values_to = "value") %>% 
  mutate(reason=recode(reason,
                       "TR_D22_1"="Theoretical Knowledge",
                       "TR_D22_2"="Practical Skills",
                       "TR_D22_3"="Languages",
                       "TR_D22_5"="Personal and Social Skills",
                       "TR_D22_6"="Management and Entrepreneurship",
                       "TR_D22_4"="IT and Computer Skills",
                       )) %>% 
  mutate(value=case_when(
    value==1 ~ FACTOR,
    TRUE ~0
  )) %>% 
  group_by(AMBITO,reason) %>% 
  summarise(FACTOR=sum(FACTOR),
            total_reason=sum(value)) %>% 
  mutate(percentage=total_reason/FACTOR*100) %>% 
  select(AMBITO,reason,percentage) ->factors
  

factors %>%
  ggplot(aes(x=percentage,y=AMBITO,,color=reason)) +
  # geom_segment(color = "gray80", size = .1) +
  geom_point()+
  theme_test()

```



